INSERT INTO `LetsTalk`.`Topic` VALUES ('Abuse');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Addictions');
INSERT INTO `LetsTalk`.`Topic` VALUES ('AIDS');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Alcohol Abuse');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Anger');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Anxiety');
INSERT INTO `LetsTalk`.`Topic` VALUES ('ADD');
INSERT INTO `LetsTalk`.`Topic` VALUES ('ADHD');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Bipolar Problems');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Bullying');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Communication and Assertion Skills');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Depression');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Disabilities');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Diversity');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Drugs');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Eating Disorder');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Gender Identity');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Grief');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Mental Illness');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Military Therapy');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Mood Disorders');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Relationships');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Relaxation and Stress Relief');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Sexual Orientation');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Sexual Communication');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Sleep');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Sport Therapy');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Social Anxiety');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Stress');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Substance Abuse');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Suicide');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Veteran Therapy');
INSERT INTO `LetsTalk`.`Topic` VALUES ('Withdrawal');
