INSERT INTO `LetsTalk`.`Topics` VALUES ('Abuse');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Addictions');
INSERT INTO `LetsTalk`.`Topics` VALUES ('AIDS');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Alcohol Abuse');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Anger');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Anxiety');
INSERT INTO `LetsTalk`.`Topics` VALUES ('ADD');
INSERT INTO `LetsTalk`.`Topics` VALUES ('ADHD');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Bipolar Problems');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Bullying');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Communication and Assertion Skills');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Depression');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Disabilities');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Diversity');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Drugs');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Eating Disorder');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Gender Identity');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Grief');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Mental Illness');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Military Therapy');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Mood Disorders');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Relationships');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Relaxation and Stress Relief');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Sexual Orientation');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Sexual Communication');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Sleep');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Sport Therapy');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Social Anxiety');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Stress');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Substance Abuse');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Suicide');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Veteran Therapy');
INSERT INTO `LetsTalk`.`Topics` VALUES ('Withdrawal');
