INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Abyssinian');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Adelie Penguin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Affenpinscher');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Afghan Hound');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('African Bush Elephant');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('African Civet');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('African Clawed Frog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('African Forest Elephant');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('African Palm Civet');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('African Penguin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('African Tree Toad');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('African Wild Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Ainu Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Airedale Terrier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Akbash');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Akita');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Alaskan Malamute');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Albatross');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Aldabra Giant Tortoise');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Alligator');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Alpine Dachsbracke');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('American Bulldog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('American Cocker Spaniel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('American Coonhound');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('American Eskimo Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('American Foxhound');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('American Pit Bull Terrier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('American Staffordshire Terrier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('American Water Spaniel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Anatolian Shepherd Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Angelfish');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Ant');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Anteater');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Antelope');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Appenzeller Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Arctic Fox');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Arctic Hare');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Arctic Wolf');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Armadillo');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Asian Elephant');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Asian Giant Hornet');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Asian Palm Civet');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Asiatic Black Bear');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Australian Cattle Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Australian Kelpie Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Australian Mist');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Australian Shepherd');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Australian Terrier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Avocet');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Axolotl');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Aye Aye');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Baboon');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bactrian Camel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Badger');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Balinese');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Banded Palm Civet');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bandicoot');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Barb');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Barn Owl');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Barnacle');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Barracuda');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Basenji Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Basking Shark');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Basset Hound');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bat');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bavarian Mountain Hound');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Beagle');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bear');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bearded Collie');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bearded Dragon');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Beaver');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bedlington Terrier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Beetle');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bengal Tiger');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bernese Mountain Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bichon Frise');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Binturong');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bird');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Birds Of Paradise');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Birman');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bison');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Black Bear');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Black Rhinoceros');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Black Russian Terrier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Black Widow Spider');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bloodhound');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Blue Lacy Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Blue Whale');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bluetick Coonhound');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bobcat');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bolognese Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bombay');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bongo');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bonobo');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Booby');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Border Collie');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Border Terrier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bornean Orang-utan');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Borneo Elephant');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Boston Terrier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bottle Nosed Dolphin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Boxer Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Boykin Spaniel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Brazilian Terrier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Brown Bear');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Budgerigar');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Buffalo');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bull Mastiff');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bull Shark');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bull Terrier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bulldog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bullfrog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Bumble Bee');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Burmese');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Burrowing Frog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Butterfly');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Butterfly Fish');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Caiman');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Caiman Lizard');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Cairn Terrier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Camel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Canaan Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Capybara');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Caracal');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Carolina Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Cassowary');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Cat');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Caterpillar');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Catfish');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Cavalier King Charles Spaniel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Centipede');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Cesky Fousek');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Chameleon');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Chamois');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Cheetah');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Chesapeake Bay Retriever');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Chicken');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Chihuahua');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Chimpanzee');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Chinchilla');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Chinese Crested Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Chinook');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Chinstrap Penguin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Chipmunk');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Chow Chow');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Cichlid');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Clouded Leopard');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Clown Fish');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Clumber Spaniel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Coati');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Cockroach');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Collared Peccary');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Collie');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Common Buzzard');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Common Frog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Common Loon');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Common Toad');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Coral');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Cottontop Tamarin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Cougar');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Cow');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Coyote');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Crab');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Crab-Eating Macaque');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Crane');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Crested Penguin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Crocodile');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Cross River Gorilla');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Curly Coated Retriever');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Cuscus');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Cuttlefish');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Dachshund');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Dalmatian');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Deer');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Desert Tortoise');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Deutsche Bracke');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Dhole');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Dingo');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Discus');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Doberman Pinscher');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Dodo');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Dogo Argentino');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Dogue De Bordeaux');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Dolphin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Donkey');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Dormouse');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Dragonfly');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Drever');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Duck');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Dugong');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Dunker');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Eagle');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Earwig');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Eastern Gorilla');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Eastern Lowland Gorilla');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Echidna');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Edible Frog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Egyptian Mau');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Electric Eel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Elephant');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Elephant Seal');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Elephant Shrew');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Emperor Penguin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Emperor Tamarin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Emu');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('English Cocker Spaniel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('English Shepherd');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('English Springer Spaniel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Entlebucher Mountain Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Epagneul Pont Audemer');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Eskimo Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Estrela Mountain Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Falcon');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Fennec Fox');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Ferret');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Field Spaniel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Fin Whale');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Finnish Spitz');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Fire-Bellied Toad');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Fish');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Fishing Cat');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Flamingo');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Flat Coat Retriever');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Flounder');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Fly');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Flying Squirrel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Fossa');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Fox');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Fox Terrier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('French Bulldog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Frigatebird');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Frilled Lizard');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Frog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Fur Seal');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Galapagos Penguin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Galapagos Tortoise');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Gar');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Gecko');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Gentoo Penguin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Geoffroys Tamarin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Gerbil');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('German Pinscher');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('German Shepherd');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Gharial');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Giant African Land Snail');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Giant Clam');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Giant Panda Bear');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Giant Schnauzer');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Gibbon');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Gila Monster');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Giraffe');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Glass Lizard');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Glow Worm');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Goat');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Golden Lion Tamarin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Golden Oriole');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Golden Retriever');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Goose');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Gopher');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Gorilla');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Grasshopper');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Great Dane');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Great White Shark');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Greater Swiss Mountain Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Green Bee-Eater');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Greenland Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Grey Mouse Lemur');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Grey Reef Shark');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Grey Seal');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Greyhound');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Grizzly Bear');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Grouse');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Guinea Fowl');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Guinea Pig');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Guppy');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Hammerhead Shark');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Hamster');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Hare');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Harrier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Havanese');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Hedgehog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Hercules Beetle');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Hermit Crab');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Heron');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Highland Cattle');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Himalayan');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Hippopotamus');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Honey Bee');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Horn Shark');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Horned Frog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Horse');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Horseshoe Crab');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Howler Monkey');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Human');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Humboldt Penguin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Hummingbird');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Humpback Whale');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Hyena');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Ibis');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Ibizan Hound');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Iguana');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Impala');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Indian Elephant');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Indian Palm Squirrel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Indian Rhinoceros');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Indian Star Tortoise');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Indochinese Tiger');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Indri');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Insect');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Irish Setter');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Irish WolfHound');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Jack Russel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Jackal');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Jaguar');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Japanese Chin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Japanese Macaque');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Javan Rhinoceros');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Javanese');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Jellyfish');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Kakapo');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Kangaroo');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Keel Billed Toucan');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Killer Whale');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('King Crab');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('King Penguin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Kingfisher');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Kiwi');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Koala');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Komodo Dragon');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Kudu');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Labradoodle');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Labrador Retriever');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Ladybird');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Leaf-Tailed Gecko');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Lemming');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Lemur');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Leopard');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Leopard Cat');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Leopard Seal');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Leopard Tortoise');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Liger');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Lion');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Lionfish');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Little Penguin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Lizard');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Llama');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Lobster');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Long-Eared Owl');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Lynx');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Macaroni Penguin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Macaw');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Magellanic Penguin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Magpie');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Maine Coon');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Malayan Civet');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Malayan Tiger');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Maltese');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Manatee');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Mandrill');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Manta Ray');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Marine Toad');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Markhor');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Marsh Frog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Masked Palm Civet');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Mastiff');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Mayfly');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Meerkat');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Millipede');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Minke Whale');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Mole');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Molly');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Mongoose');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Mongrel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Monitor Lizard');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Monkey');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Monte Iberia Eleuth');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Moorhen');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Moose');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Moray Eel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Moth');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Mountain Gorilla');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Mountain Lion');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Mouse');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Mule');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Neanderthal');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Neapolitan Mastiff');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Newfoundland');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Newt');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Nightingale');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Norfolk Terrier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Norwegian Forest');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Numbat');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Nurse Shark');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Ocelot');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Octopus');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Okapi');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Old English Sheepdog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Olm');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Opossum');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Orang-utan');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Ostrich');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Otter');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Oyster');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Pademelon');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Panther');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Parrot');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Patas Monkey');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Peacock');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Pekingese');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Pelican');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Penguin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Persian');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Pheasant');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Pied Tamarin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Pig');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Pika');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Pike');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Pink Fairy Armadillo');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Piranha');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Platypus');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Pointer');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Poison Dart Frog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Polar Bear');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Pond Skater');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Poodle');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Pool Frog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Porcupine');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Possum');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Prawn');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Proboscis Monkey');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Puffer Fish');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Puffin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Pug');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Puma');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Purple Emperor');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Puss Moth');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Pygmy Hippopotamus');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Pygmy Marmoset');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Quail');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Quetzal');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Quokka');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Quoll');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Rabbit');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Raccoon');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Raccoon Dog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Radiated Tortoise');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Ragdoll');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Rat');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Rattlesnake');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Red Knee Tarantula');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Red Panda');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Red Wolf');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Red-handed Tamarin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Reindeer');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Rhinoceros');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('River Dolphin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('River Turtle');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Robin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Rock Hyrax');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Rockhopper Penguin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Roseate Spoonbill');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Rottweiler');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Royal Penguin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Russian Blue');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sabre-Toothed Tiger');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Saint Bernard');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Salamander');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sand Lizard');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Saola');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Scorpion');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Scorpion Fish');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sea Dragon');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sea Lion');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sea Otter');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sea Slug');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sea Squirt');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sea Turtle');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sea Urchin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Seahorse');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Seal');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Serval');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sheep');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Shih Tzu');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Shrimp');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Siamese');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Siamese Fighting Fish');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Siberian');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Siberian Husky');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Siberian Tiger');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Silver Dollar');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Skunk');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sloth');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Slow Worm');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Snail');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Snake');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Snapping Turtle');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Snowshoe');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Snowy Owl');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Somali');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('South China Tiger');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Spadefoot Toad');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sparrow');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Spectacled Bear');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sperm Whale');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Spider Monkey');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Spiny Dogfish');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sponge');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Squid');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Squirrel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Squirrel Monkey');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sri Lankan Elephant');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Staffordshire Bull Terrier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Stag Beetle');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Starfish');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Stellers Sea Cow');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Stick Insect');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Stingray');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Stoat');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Striped Rocket Frog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sumatran Elephant');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sumatran Orang-utan');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sumatran Rhinoceros');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sumatran Tiger');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Sun Bear');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Swan');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Tang');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Tapir');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Tarsier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Tasmanian Devil');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Tawny Owl');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Termite');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Tetra');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Thorny Devil');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Tibetan Mastiff');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Tiffany');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Tiger');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Tiger Salamander');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Tiger Shark');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Tortoise');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Toucan');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Tree Frog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Tropicbird');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Tuatara');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Turkey');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Turkish Angora');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Uakari');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Uguisu');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Umbrellabird');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Vampire Bat');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Vervet Monkey');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Vulture');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Wallaby');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Walrus');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Warthog');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Wasp');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Water Buffalo');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Water Dragon');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Water Vole');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Weasel');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Welsh Corgi');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('West Highland Terrier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Western Gorilla');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Western Lowland Gorilla');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Whale Shark');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Whippet');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('White Faced Capuchin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('White Rhinoceros');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('White Tiger');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Wild Boar');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Wildebeest');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Wolf');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Wolverine');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Wombat');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Woodlouse');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Woodpecker');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Woolly Mammoth');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Woolly Monkey');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Wrasse');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('X-Ray Tetra');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Yak');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Yellow-Eyed Penguin');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Yorkshire Terrier');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Zebra');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Zebra Shark');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Zebu');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Zonkey');
INSERT INTO `LetsTalk`.`UserNouns` VALUES ('Zorse');
